# 
# policy_path: "{LEGGED_GYM_ROOT_DIR}/logs/a1/exported/motion.pt"
policy_path: "{LEGGED_GYM_ROOT_DIR}/logs/a1_23dof/exported/policies/policy_lstm_1.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/a1/scene_Arcus_23dof.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10


kps: [
      100, 100, 100, # left hip 
      150,           # left knee 
      40, 40,        # left ankle
      100, 100, 100, # right hip
      150,           # right knee
      40, 40,        # right ankle       

      250,           # waist

      100, 100, 100, # left shoulder
      50, 50,        # left elbow/wrist 
      100, 100, 100, # right shoulder
      50, 50        # right elbow/wrist 
      ]
kds: [
      2, 2, 2, 
      4, 
      2, 2, 
      2, 2, 2, 
      4,
      2, 2, 

      6, 

      2, 2, 2, 
      2, 2, 
      2, 2, 2, 
      2, 2
      ]

default_angles: [
                -0.1, 0.0,  0.0,
                0.3,
                -0.2, 0.0, 
                -0.1, 0.0,  0.0,
                0.3,
                -0.2, 0.0,

                0.0,

                0.0, 0.0,  0.0,
                0.0, 0.0,
                0.0, 0.0,  0.0,
                0.0, 0.0
                ]


ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 23
num_obs: 80

cmd_init: [0.5, 0, 0]